import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  users: defineTable({
    email: v.string(),
    normalizedEmail: v.string(),
    createdAt: v.number(),
    lastSeenAt: v.number(),
    status: v.string(),
    source: v.string(),
    consentVersion: v.string(),
    activatedAt: v.optional(v.number()),
  }).index("by_normalized_email", ["normalizedEmail"]),
  anonymousSessions: defineTable({
    sessionHash: v.string(),
    firstSeenAt: v.number(),
    lastSeenAt: v.number(),
    firstReferrer: v.optional(v.string()),
    userAgentHash: v.optional(v.string()),
    coarseCountry: v.optional(v.string()),
    convertedUserId: v.optional(v.id("users")),
  }).index("by_session_hash", ["sessionHash"]),
  researchProfiles: defineTable({
    platform: v.string(),
    normalizedHandle: v.string(),
    displayHandle: v.string(),
    evidence: v.array(v.string()),
    sourceURLs: v.array(v.string()),
    confidence: v.number(),
    provider: v.string(),
    providerRequestId: v.optional(v.string()),
    queryVersion: v.string(),
    createdAt: v.number(),
    expiresAt: v.number(),
    status: v.string(),
    errorCategory: v.optional(v.string()),
  }).index("by_platform_handle_version", [
    "platform",
    "normalizedHandle",
    "queryVersion",
  ]),
  generations: defineTable({
    publicId: v.string(),
    sessionHash: v.string(),
    userId: v.optional(v.id("users")),
    researchProfileId: v.optional(v.id("researchProfiles")),
    status: v.string(),
    archetypeVersion: v.string(),
    promptVersion: v.string(),
    model: v.string(),
    requestId: v.string(),
    latencyMs: v.optional(v.number()),
    estimatedCost: v.optional(v.number()),
    retryCount: v.number(),
    errorCode: v.optional(v.string()),
    idempotencyKey: v.string(),
    createdAt: v.number(),
    completedAt: v.optional(v.number()),
  })
    .index("by_public_id", ["publicId"])
    .index("by_idempotency_key", ["idempotencyKey"])
    .index("by_session_created", ["sessionHash", "createdAt"]),
  cards: defineTable({
    generationId: v.id("generations"),
    slug: v.string(),
    cardData: v.any(),
    imageURL: v.optional(v.string()),
    audioURL: v.optional(v.string()),
    isPublic: v.boolean(),
    createdAt: v.number(),
    version: v.string(),
    ownerUserId: v.optional(v.id("users")),
    emailSavedAt: v.optional(v.number()),
  })
    .index("by_slug", ["slug"])
    .index("by_generation", ["generationId"]),
  generatedCards: defineTable({
    publicId: v.string(),
    sessionId: v.string(),
    handle: v.string(),
    archetypeId: v.string(),
    card: v.any(),
    researchConfidence: v.number(),
    model: v.string(),
    promptVersion: v.string(),
    taxonomyVersion: v.string(),
    durationMs: v.number(),
    retryCount: v.number(),
    viewedAt: v.optional(v.number()),
    emailSavedAt: v.optional(v.number()),
    createdAt: v.number(),
  })
    .index("by_public_id", ["publicId"])
    .index("by_handle", ["handle"]),
  referrals: defineTable({
    referrerUserId: v.optional(v.id("users")),
    referrerCardId: v.string(),
    referralCode: v.string(),
    referredSessionHash: v.string(),
    referredUserId: v.optional(v.id("users")),
    status: v.string(),
    creditedAt: v.optional(v.number()),
    idempotencyKey: v.string(),
    createdAt: v.number(),
  })
    .index("by_referral_code", ["referralCode"])
    .index("by_referred_session", ["referredSessionHash"])
    .index("by_idempotency_key", ["idempotencyKey"]),
  challenges: defineTable({
    slug: v.string(),
    challengerCardId: v.string(),
    challengerSessionHash: v.string(),
    targetHandle: v.optional(v.string()),
    acceptedCardId: v.optional(v.string()),
    acceptedSessionHash: v.optional(v.string()),
    status: v.string(),
    result: v.optional(v.any()),
    referralCredited: v.boolean(),
    createdAt: v.number(),
    completedAt: v.optional(v.number()),
  }).index("by_slug", ["slug"]),
  credits: defineTable({
    userId: v.id("users"),
    reason: v.string(),
    amount: v.number(),
    idempotencyKey: v.string(),
    createdAt: v.number(),
  })
    .index("by_user", ["userId"])
    .index("by_idempotency_key", ["idempotencyKey"]),
  leaderboard: defineTable({
    cardId: v.string(),
    handle: v.string(),
    aura: v.number(),
    archetypeId: v.string(),
    eligible: v.boolean(),
    updatedAt: v.number(),
  }).index("by_aura", ["eligible", "aura"]),
  shareEvents: defineTable({
    cardId: v.string(),
    userId: v.optional(v.id("users")),
    sessionHash: v.string(),
    channel: v.string(),
    createdAt: v.number(),
  }).index("by_card", ["cardId"]),
  audioStatus: defineTable({
    cardId: v.string(),
    status: v.string(),
    storageUrl: v.optional(v.string()),
    errorCategory: v.optional(v.string()),
    updatedAt: v.number(),
  }).index("by_card", ["cardId"]),
  payments: defineTable({
    provider: v.string(),
    externalPaymentId: v.string(),
    userId: v.optional(v.id("users")),
    product: v.string(),
    amount: v.number(),
    currency: v.string(),
    status: v.string(),
    createdAt: v.number(),
  }).index("by_external_payment", ["provider", "externalPaymentId"]),
  auditEvents: defineTable({
    actorType: v.string(),
    actorId: v.optional(v.string()),
    action: v.string(),
    resourceType: v.string(),
    resourceId: v.optional(v.string()),
    metadata: v.optional(v.any()),
    requestId: v.optional(v.string()),
    createdAt: v.number(),
  }).index("by_action_created", ["action", "createdAt"]),
  generationStatus: defineTable({
    publicId: v.string(),
    status: v.string(),
    step: v.string(),
    errorCategory: v.optional(v.string()),
    updatedAt: v.number(),
  }).index("by_public_id", ["publicId"]),
});
